document.querySelector('.new-quote').addEventListener('click', ()=>{
    let text = document.querySelector('.quote')
    let author = document.querySelector('.author')
    
    let quotes = [
        {quote: 'True terror is to wake up one morning and discover that your high school classs is running the country.', 
        person: 'Kurt Vonnegut'},
        {quote: 'Doing nothing is very hard to do. You never know when you are finished.', 
        person: 'Leslie Nielsen'},
        {quote: 'Dont wait around for other people to be happy for you. Any happiness you get you haveve got to make yourself', 
        person: 'Alice Walker'},
        {quote: 'Morality is only moral when it is voluntary.', 
        person: 'Lincoln Steffens'},
        {quote: 'One of the lessons of history is that nothing is often a good thing to do and always a clever thing to say', 
        person: 'Will Durant'},
        {quote: 'It is a funny thing about life; if you refuse to accept anything but the best, you very often get it.', 
        person: 'W. Somerset Maugham'},
        {quote: 'The best way to predict the future is to create it.', 
        person: 'Peter F. Drucker'},
        {quote: 'Amateurs wait for inspiration. The rest of us just get up and go to work', 
        person: 'Chuck Close'},
        {quote: 'If you have a job without any aggravations, you don’t have a job.', 
        person: 'Malcolm Forbes'},
        {quote: 'If you are too careful, you are so occupied in being careful that you are sure to stumble over something.', 
        person: 'Gertrude Stein'},
        {quote: 'Be like a duck. Calm on the surface but always paddling like the dickens underneath.', 
        person: 'Michael Caine'},
        {quote: 'One of the best parts of growing older? You can flirt all you like since you’ve become harmless.', 
        person: 'Liz Smith'},
        {quote:'I have no special talent. I am only passionately curious',
        person:'Albert Einstein'},
        {quote:'Whenever you find yourself on the side of the majority, it is time to pause and reflect.',
        person:'Mark Twain'},
        {quote:'All that we are is the result of what we have thought',
        person:'Buddha'},
        {quote:'Ask not what your country can do for you, but what you can do for your country.',
        person:'John F. Kennedy'},
        {quote:'No matter who you are or what you look like, how you started off, or how and who you love, America is a place where you can write your own destiny.',
        person:'Barack Obama'},
        {quote:'You have power over your mind – not outside events. Realize this, and you will find strength.',
        person:'Marcus Aurelius'},
        {quote:'I have a dream that one day little black boys and girls will be holding hands with little white boys and girls.',
        person:'Martin Luther Jr.'},
        {quote:'It is you, the young and fearless at heart, the most diverse and educated generation in our history, who the nation is waiting to follow.',
        person:'Barack Obama'},
        {quote:'For beautiful eyes, look for the good in others; for beautiful lips, speak only words of kindness; and for poise, walk with the knowledge that you are never alone.',
        person:'Audrey Hepburn'},
        {quote:'Do all the good you can, for all the people you can, in all the ways you can, as long as you can.',
        person:'Hillary Clinton'},
        {quote:'If people take anything from my music, it should be motivation to know that anything is possible as long as you keep working at it and dont back down.',
        person:'Eminem'},
        {quote:'I have learned over the years that when one’s mind is made up, this diminishes fear; knowing what must be done does away with fear.',
        person:'Rosa Parks'},
        {quote:'If I have seen further than others, it is by standing upon the shoulders of giants.',
        person:'Isaac Newton'},
        {quote:'Learn to value yourself, which means: to fight for your happiness.',
        person:'Ayn Rand'},
        {quote:'To know that we know what we know, and to know that we do not know what we do not know, that is true knowledge',
        person:'Nicolaus Copernicus'},
        {quote:'Too often we enjoy the comfort of opinion without the discomfort of thought.',
        person:'John F. Kennedy'},
        {quote:'A fool thinks himself to be wise, but a wise man knows himself to be a fool.',
        person:'William Shakespeare'},
        {quote:'There is nothing so useless as doing efficiently that which should not be done at all.',
        person:'Peter Drucker'},
        

        ];

    let index= Math.floor(Math.random()* quotes.length)
    text.innerText = quotes[index].quote
    author.innerText = quotes[index].person
})